### ISSUE TITLE
Implementare Tab Anunturi

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/anaf-mobile#16]
Categorii:
- [x] Achizitie de bunuri si servicii
- [x] Acte administrative fiscale
- [x] Executari silite cu dare in plata
- [x] Loteria bonurilor fiscale
- [x] Angajari/Concursuri
- [x] Anunturi de interes general

Specificatie: https://contribute.gov.ro/confluence/display/APPANAF/Anunturi

Dependent: #8, #25

**Comment by gpanainte** [comment]
implementat
