### ISSUE TITLE
Implementare Tab Comunicate de presa

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/anaf-mobile#28]
Specs: https://contribute.gov.ro/confluence/display/APPANAF/Comunicate+de+presa
Dependent: #25 

Features (lista):
- [x] General (ANAF RSS)
- [x] Bucuresti
- [x] Iasi
- [x] Galati
- [x] Ploiesti
- [x] Craiova
- [x] Timisoara
- [x] Cluj
- [x] Brasov

Similar alte liste RSS

**Comment by gpanainte** [comment]
implementat
