### ISSUE TITLE
Style Guide -  "Colors" si "Typography" folosite in aplicatie

### ISSUE THREAD

**Issue by DanielCornea** [gov-ithub/anaf-mobile#5]
[ANAF-mobile.zip](https://github.com/gov-ithub/anaf-mobile/files/654879/ANAF-mobile.zip)

**Comment by DanielCornea** [comment]
[
[ANAF Mobile - Style Guide.pdf](https://github.com/gov-ithub/anaf-mobile/files/654859/ANAF.Mobile.-.Style.Guide.pdf)
](url)

**Comment by alexchiraples** [comment]
duplicate #9 
Am adaugat fisierele in docs/layout
