### ISSUE TITLE
Creare serviciu citire rss feed

### ISSUE THREAD

**Issue by gpanainte** [gov-ithub/anaf-mobile#8]
Prototip citire achizitie de bunuri si servicii

https://contribute.gov.ro/confluence/display/APPANAF/Anunturi
https://www.anaf.ro/ANAFRSS/?canal=achizBS

- [x] RSS to JSON service
- [x] Lista ce afiseaza feed-ul rss cu link-uri catre url-urile primite

**Comment by gpanainte** [comment]
- rss service created
- rss feed component created

**Comment by alexchiraples** [comment]
Opened: Am facut revert la PR #12. Detalii in #14
