### ISSUE TITLE
Variabilele SASS si stilurile globale

### ISSUE THREAD

**Issue by arizona2014** [gov-ithub/anaf-mobile#9]
Crearea variabilelor proiectului in fisierul variables.scss si a stilurilor globale aplicatiei.

**Comment by alexchiraples** [comment]
Style guide:
https://github.com/gov-ithub/anaf-mobile/blob/master/docs/layout/ANAF%20Mobile%20-%20Style%20Guide.pdf

Icons:
https://github.com/gov-ithub/anaf-mobile/tree/master/docs/layout/icomoon-iconfont

Wireframes:
https://github.com/gov-ithub/anaf-mobile/tree/master/docs/layout/wireframes
